# Generated by Django 3.2.8 on 2021-11-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namePlace', models.CharField(max_length=30, verbose_name='Name')),
            ],
        ),
    ]
